### ISSUE TITLE
总体好评！

### ISSUE THREAD

**Issue by twhy** [totorozhao/jirengu#1]
改善建议
1. 可以通过 `input::-webkit-input-placeholder: { color: #ccc; }` 给 placeholder 设置字体颜色。
2. 注册和登录之间有点间隙是 `inline-block` 产生的，试试怎么把那个间隙去掉。
3. 注册知乎 和 下载知乎App 按钮高度应该是 41px，你的是 46px，建议设置 `padding: 0` 把浏览器默认样式去掉。

**Comment by totorozhao** [comment]
谢谢老师建议,已更改。
